# Generated by Django 4.2.5 on 2023-09-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTODO', '0002_premios_tareas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
